In [44]:
import numpy as np
# prob of success
p = 0.869 
# prob of failuare
q = 1-p

n = 3

k = np.arange(0,4)

print(k)

[0 1 2 3]


In [35]:
from scipy.stats import binom

binomial_with_p = binom.pmf(k,n,p)

print("zero success one success two success three success")

print(binomial_with_p)
print("3 error 2 error 1 error 0 error")

zero success one success two success three success
[0.00224809 0.04473873 0.29677827 0.65623491]
3 error 2 error 1 error 0 error


In [36]:
binomial_with_q = binom.pmf(k,n,q)

print("zero error one error two error three error")

print(binomial_with_q)
print("3 success 2 success 1 success 0 success")


zero error one error two error three error
[0.65623491 0.29677827 0.04473873 0.00224809]
3 success 2 success 1 success 0 success


In [22]:
binomial_test_q= binom.pmf(0,n,q)
binomial_test_q

0.656234909

In [50]:
binomial_test_p= binom.pmf(0,n,p)
binomial_test_p

0.0022480910000000002

In [52]:
# All three orders are filled correctly
print('All the three orders are filled correctly? is %1.4f' %binomial_with_q[0])

# None of the three orders are filled correctly
print('None of the three orders are filled incorrectly? is %1.4f' %binomial_with_q[3])



All the three orders are filled correctly? is 0.6562
None of the three orders are filled incorrectly? is 0.0022


In [53]:
# At most two of the three orders will be filled correctly
# at most 2 means maximum will be 2 minimum can be 0 or 1
cumbinomial = list(binom.cdf(k,n,p))

print("At most 0 correct at most 1 correct at most 2 correct at most 3 correct")

print(cumbinomial)

print('At most two of the three orders are filled correctly ? is %1.4f' % cumbinomial[2])

At most 0 correct at most 1 correct at most 2 correct at most 3 correct
[0.0022480910000000002, 0.04698681800000001, 0.34376509099999997, 1.0]
At most two of the three orders are filled correctly ? is 0.3438


In [58]:
cumbinomial = list(binom.cdf(k,n,q))
cumbinomial

[0.656234909, 0.953013182, 0.997751909, 1.0]

In [29]:
binomial_with_p[0]+binomial_with_p[1]+binomial_with_p[2]

0.3437650910000001

In [39]:
# At least two of three orders are filled correctly?
# minimun is 2 maximum can be 3
binomial_with_p[2]+binomial_with_p[3]

0.9530131820000001

In [55]:
1-cumbinomial[2-1]

0.953013182

In [56]:
cumbinomial

[0.0022480910000000002, 0.04698681800000001, 0.34376509099999997, 1.0]